export const projects = [
  {
    id: 3,
    name: 'Kuk, a cooking app.',
    bgImg: '/images/kuk.png',
    alt: 'Kuk Logo',
    logoImg: '/logos/logokuk.png',
    descripcion:
      "The joy of flipping through mom's recipe book is brought into the digital age with Kuk. Your kitchen companion just a tap away.",
    descripcionModal:
      'Kuk, an app for beginners in homemade cooking. Provides a customizable meal diary to manage time and money.',
    serviceType: 'UX/UI',
    linkToWeb: 'https://www.behance.net/gallery/164030461/Kuk-a-cooking-app',
    modalImgOne: '/images/kuk1.png',
    modalImgTwo: '/images/kuk2.png',
    modalImgThree: '/images/kuk3.png',
    modalImgFour: '/images/kuk4.png',
    modalImgFive: '/images/kuk5.png',
    pathToPage: '/kuk',
  },
  {
    id: 6,
    name: 'Interpreters UI',
    bgImg: '/images/IUIbg.png',
    alt: 'IUI Logo',
    logoImg: '/images/IUILogo.png',
    descripcion:
      'UX/UI Design for the interpreters industry. Interface and user experience design for interpreters dashboard.',
    descripcionModal:
      'Dashboards for over-the-phone interpretation. Renovation of the user interface for the interpreters dashboard.',
    serviceType: 'UX/UI',
    linkToWeb:
      'https://www.behance.net/gallery/172288583/IUI-a-dashboard-for-interpretation',
    modalImgOne: '/images/iui1.png',
    modalImgTwo: '/images/iui2.png',
    modalImgThree: '',
    modalImgFour: '',
    modalImgFive: '/images/iui5.png',
    pathToPage: '/IUI',
  },
  {
    id: 5,
    name: 'Giko [+]',
    bgImg: '/images/GIKO.png',
    alt: 'Giko Logo',
    logoImg: '/logos/logogiko.png',
    descripcion:
      'Giko is a peripherals retailer specialized in mechanical keyboards. Less is definitely more.',
    descripcionModal:
      'Completo diseño de marca para Giko [+]. Desarrollo de identidad y posicionamiento de marca dentro del rubro de teclados mecánicos.',
    serviceType: 'Brand',
    linkToWeb: 'https://www.zerendor.com/',
    modalImgOne: '/images/giko1.png',
    modalImgTwo: '/images/giko2.png',
    modalImgThree: '/images/giko3.png',
    modalImgFour: '/images/giko4.png',
    modalImgFive: '/images/giko5.png',
    pathToPage: '/giko',
  },
  {
    id: 4,
    name: 'Zerendor.com',
    bgImg: '/images/zerendorpuntocom.png',
    alt: 'Zerendor Logo',
    logoImg: '/logos/logozere.png',
    descripcion:
      'Design is the solution. zerendor.com. Passion is key. zerendor.com. Discipline is success. zerendor.com.',
    descripcionModal:
      'El diseño es la solución. zerendor.com. La pasión es la clave. zerendor.com. La disciplina es el éxito. zerendor.com. Webdev for zerendor.com.',
    serviceType: 'Webdev',
    linkToWeb: 'https://www.zerendor.com/',
    modalImgOne: '/images/zere1.png',
    modalImgTwo: '/images/zere2.png',
    modalImgThree: '/images/zere3.png',
    modalImgFour: '/images/zere4.png',
    modalImgFive: '/images/zere5.png',
    pathToPage: '/zere',
  },
  {
    id: 2,
    name: 'Spatial Awareness',
    bgImg: '/images/spaw.png',
    alt: 'Spaw Logo',
    logoImg: '/logos/logospaw.png',
    descripcion:
      'A brand that thrives on the reminiscence of simpler times, established in an obsessed passion for well designed things.',
    descripcionModal:
      'SPAW is a brand that encompasses several fields, hence the need to have an everchanging but recognizable logo. A brand that thrives on the reminiscence of simpler times.',
    serviceType: 'Brand',
    linkToWeb: 'https://www.behance.net/gallery/180826501/Brands-x-SPAW',
    modalImgOne: '/images/spaw1.png',
    modalImgTwo: '/images/spaw2.png',
    modalImgThree: '/images/spaw3.png',
    modalImgFour: '/images/spaw4.png',
    modalImgFive: '/images/spaw5.png',
    pathToPage: '/spaw',
  },
  // {
  //   id: 1,
  //   name: '(magnet)',
  //   bgImg: '/images/magnetbg.png',
  //   alt: 'Magnet Logo',
  //   logoImg: '/logos/logomagnet.png',
  //   descripcion:
  //     'Un nuevo comienzo. Acompáñanos a ser líderes globales en transformación de emprendedores. Conoce más sobre magnet y su universo creativo aquí.',
  //   descripcionModal:
  //     'El mejor ejemplo de nuestro estándar de trabajo y de la calidad que obtendrás. Diseño y Desarrollo completo de marca.',
  //   serviceType: 'Brand - Webdev',
  //   linkToWeb: '/',
  //   modalImgOne: '/images/magnet1.png',
  //   modalImgTwo: '/images/magnetBg.png',
  //   modalImgThree: '/images/magnet3.png',
  //   modalImgFour: '/logos/white-logo.svg',
  //   modalImgFive: '/images/magnet5.png',
  //   pathToPage: '/magnet',
  // },
];
